pipeline{

    agent any

    //here we define the parameters for the test environment, so we can setup which SPEC to test
    // and also which Browser to use, for instance chrome, edge or firefox
    parameters{
        string(name: 'SPEC', defaultValue: "src/Tests/**/**", description: "Enter script path")
        choice (name: 'BROWSER', choices ['chrome','edge','firefox'], description:"Choose the browser")
    }

    options{
        ansiColor('xterm')
    }

    stages{
        stage('Building'){
            steps{
                echo "Building the application"
            }
        }
        
        stage('Testing'){
            steps{
                bat "npm i"
                bat " npx cypress run --browser ${BROWSER} --spec ${SPEC}"
            }
        }

         stage('Deploying'){
            steps{
                echo "Deploying the application"
            }
        }
    }
}